### ISSUE TITLE
Changing the skin causes the server to crash

### ISSUE THREAD

**Issue by andriycraft** [BlueBirdMC/BlueBird#6]

**Comment by andriycraft** [comment]
C:\Users\User\Desktop\BlueBird-main\src\network\mcpe\protocol\types\SkinImage.js:45
                throw new Error("Unknown size");
                ^

Error: Unknown size
    at Function.fromLegacy (C:\Users\User\Desktop\BlueBird-main\src\network\mcpe\protocol\types\SkinImage.js:45:9)
    at LegacySkinAdapter.toSkinData (C:\Users\User\Desktop\BlueBird-main\src\network\mcpe\protocol\types\LegacySkinAdapter.js:34:14)
    at Player.sendSkin (C:\Users\User\Desktop\BlueBird-main\src\entity\Human.js:45:46)
    at Player.changeSkin (C:\Users\User\Desktop\BlueBird-main\src\Player.js:106:8)
    at PlayerNetworkSession.handlePlayerSkin (C:\Users\User\Desktop\BlueBird-main\src\network\mcpe\PlayerNetworkSession.js:76:15)
    at PlayerSkinPacket.handle (C:\Users\User\Desktop\BlueBird-main\src\network\mcpe\protocol\PlayerSkinPacket.js:45:18)
    at PlayerNetworkSession.handleDataPacket (C:\Users\User\Desktop\BlueBird-main\src\network\mcpe\PlayerNetworkSession.js:55:10)
    at C:\Users\User\Desktop\BlueBird-main\src\network\mcpe\protocol\GamePacket.js:102:13
    at Array.forEach (<anonymous>)
    at GamePacket.handle (C:\Users\User\Desktop\BlueBird-main\src\network\mcpe\protocol\GamePacket.js:94:21)

**Comment by VaxPex** [comment]
ik

**Comment by VaxPex** [comment]
how u got it? I dont get it
